### ISSUE TITLE
update GLM version in nix and mac to 2.0.0.beta.6

### ISSUE THREAD

**Issue by jread-usgs** [GLEON/GLMr#65]
Or whatever we are calling our beta6 build with the bug fix (beta7?).

**Comment by lawinslow** [comment]
I hate to do this, but because of our (currently) slightly divergent fork, we should probably not increment their beta version. There is no telling if they will match in the future. We should probably mark it with our own suffix or something

2.0.0-beta6-usgs1

or something like that. Then, we know it is UWA beta6 code with the usgs1 patch applied. Thoughts?

**Comment by jread-usgs** [comment]
Yeah, that makes sense. Good point. We should rebuild on monday with that change in the source. 

On a different note, should we avoid releasing the GLMr package until all three platforms have the same GLM code? That is what I was thinking. So the dev GLMr on github is slightly divergent w/ windows, but the actual source release (on gleon.io) always has the same version for all 3 platforms?

**Comment by lawinslow** [comment]
Yeah, agreed. How about we agree to not push a build release to the gleon.io area until model versions are unified?

**Comment by jread-usgs** [comment]
Agreed.
