### ISSUE TITLE
Update citation for Hipsey 2014

### ISSUE THREAD

**Issue by jread-usgs** [GLEON/GLMr#89]
Currently is 2013 in package

**Comment by lawinslow** [comment]
Do you mean just change the year, or is there a 2014 GLM pub I don't know of?

**Comment by jread-usgs** [comment]
I think there is a more current citation that is a little different. I will add it here if I track it down.

**Comment by jsta** [comment]
I see a [2014 version](http://aed.see.uwa.edu.au/research/models/GLM/downloads/AED_GLM_v2_0b0_20141025.pdf) at the following page:
http://aed.see.uwa.edu.au/research/models/GLM/latest_release.html

It's a little tricky being under `Downloads -> Latest Release` rather than `Publications` or `Support`.

> Hipsey, M.R., Bruce, L.C., Hamilton, D.P., 2014. GLM - General Lake Model: Model overview and user information. AED Report #26, The University of Western Australia, Perth, Australia. 42pp.

**Comment by jread-usgs** [comment]
Yes, that one should be used

**Comment by jsta** [comment]
I think this issue can be closed.
